require("awful.hotkeys_popup.keys")
require("configs.bindings.awesome")
require("configs.bindings.client")
require("configs.bindings.launcher")
require("configs.bindings.layout")
require("configs.bindings.mouse")
require("configs.bindings.screen")
require("configs.bindings.tag")